# Generated by Django 5.1.4 on 2025-04-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('semester', models.CharField(choices=[('1', 'Sem 1'), ('2', 'Sem 2'), ('3', 'Sem 3'), ('4', 'Sem 4'), ('5', 'Sem 5'), ('6', 'Sem 6'), ('7', 'Sem 7'), ('8', 'Sem 8')], max_length=2)),
                ('course_name', models.CharField(max_length=50)),
                ('time_interval', models.CharField(choices=[('8-9 AM', '8-9 AM'), ('9-10 AM', '9-10 AM'), ('10-11 AM', '10-11 AM'), ('11-12 PM', '11-12 PM'), ('12-1 PM', '12-1 PM'), ('1-2 PM', '1-2 PM'), ('2-3 PM', '2-3 PM'), ('3-4 PM', '3-4 PM'), ('4-5 PM', '4-5 PM'), ('5-6 PM', '5-6 PM')], max_length=20)),
                ('room_no', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('class_type', models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'Lab'), ('Tutorial', 'Tutorial')], max_length=10)),
            ],
        ),
    ]
