# Generated by Django 5.1.4 on 2025-04-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentstt',
            name='time_interval',
        ),
        migrations.AddField(
            model_name='studentstt',
            name='time_slot',
            field=models.CharField(choices=[('8-9 AM', '8-9 AM'), ('9-10 AM', '9-10 AM'), ('10-11 AM', '10-11 AM'), ('11-12 PM', '11-12 PM'), ('12-1 PM', '12-1 PM'), ('1-2 PM', '1-2 PM'), ('2-3 PM', '2-3 PM'), ('3-4 PM', '3-4 PM'), ('4-5 PM', '4-5 PM'), ('5-6 PM', '5-6 PM')], default='8-9 AM', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='class_type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'Lab'), ('Tutorial', 'Tutorial')], default='Theory', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='course_name',
            field=models.CharField(default='Course', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='room_no',
            field=models.CharField(default='101', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='subject_name',
            field=models.CharField(default='Subject', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='teacher_name',
            field=models.CharField(default='Teacher', max_length=100),
        ),
    ]
