# Generated by Django 5.1.4 on 2025-04-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0003_alter_studentstt_class_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstt',
            name='batch',
            field=models.CharField(choices=[('all', 'All'), ('1', '1'), ('2', '2'), ('3', '3')], default='all', max_length=10),
        ),
    ]
