# Generated by Django 5.1.7 on 2025-05-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0004_studentstt_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultysTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('course_name', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('TY', 'TY'), ('SY', 'SY'), ('4Y', '4Y'), ('FY', 'FY')], default=None, max_length=2, null=True)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='NA', max_length=2)),
                ('time_slot', models.CharField(choices=[('8-9 AM', '8-9 AM'), ('9-10 AM', '9-10 AM'), ('10-11 AM', '10-11 AM'), ('11-12 PM', '11-12 PM'), ('12-1 PM', '12-1 PM'), ('1-2 PM', '1-2 PM'), ('2-3 PM', '2-3 PM'), ('3-4 PM', '3-4 PM'), ('4-5 PM', '4-5 PM'), ('5-6 PM', '5-6 PM')], max_length=10)),
                ('room_no', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=100)),
                ('branchName', models.CharField(max_length=100)),
                ('div', models.CharField(default='A', max_length=1)),
                ('class_type', models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'Lab'), ('Tutorial', 'Tutorial')], max_length=10)),
                ('batch', models.CharField(choices=[('all', 'All'), ('1', '1'), ('2', '2'), ('3', '3')], default='all', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='studentstt',
            name='div',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='studentstt',
            name='year',
            field=models.CharField(choices=[('TY', 'TY'), ('SY', 'SY'), ('4Y', '4Y'), ('FY', 'FY')], default=None, max_length=2, null=True),
        ),
    ]
