# Generated by Django 5.1.7 on 2025-05-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0005_facultystt_studentstt_div_studentstt_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultystt',
            name='teacher_name',
            field=models.CharField(default='Na', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facultystt',
            name='course_name',
            field=models.CharField(choices=[('MEC', 'MEC'), ('ENTC', 'ENTC'), ('CS', 'CS'), ('AIML', 'AIML'), ('AIDS', 'AIDS'), ('IT', 'IT'), ('AI', 'AI')], max_length=100),
        ),
        migrations.AlterField(
            model_name='facultystt',
            name='year',
            field=models.CharField(choices=[('SY', 'SY'), ('4Y', '4Y'), ('TY', 'TY'), ('FY', 'FY')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='course_name',
            field=models.CharField(choices=[('MEC', 'MEC'), ('ENTC', 'ENTC'), ('CS', 'CS'), ('AIML', 'AIML'), ('AIDS', 'AIDS'), ('IT', 'IT'), ('AI', 'AI')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='year',
            field=models.CharField(choices=[('SY', 'SY'), ('4Y', '4Y'), ('TY', 'TY'), ('FY', 'FY')], default=None, max_length=2, null=True),
        ),
    ]
