# Generated by Django 5.1.7 on 2025-05-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0006_facultystt_teacher_name_alter_facultystt_course_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultystt',
            name='branchName',
        ),
        migrations.AlterField(
            model_name='facultystt',
            name='course_name',
            field=models.CharField(choices=[('MEC', 'MEC'), ('AIML', 'AIML'), ('AI', 'AI'), ('CS', 'CS'), ('ENTC', 'ENTC'), ('IT', 'IT'), ('AIDS', 'AIDS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='facultystt',
            name='year',
            field=models.CharField(choices=[('FY', 'FY'), ('TY', 'TY'), ('SY', 'SY'), ('4Y', '4Y')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='course_name',
            field=models.CharField(choices=[('MEC', 'MEC'), ('AIML', 'AIML'), ('AI', 'AI'), ('CS', 'CS'), ('ENTC', 'ENTC'), ('IT', 'IT'), ('AIDS', 'AIDS')], default='AIML', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='year',
            field=models.CharField(choices=[('FY', 'FY'), ('TY', 'TY'), ('SY', 'SY'), ('4Y', '4Y')], default=None, max_length=2, null=True),
        ),
    ]
