# Generated by Django 5.1.7 on 2025-05-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0007_remove_facultystt_branchname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultystt',
            name='course_name',
            field=models.CharField(choices=[('AIDS', 'AIDS'), ('CS', 'CS'), ('AIML', 'AIML'), ('IT', 'IT'), ('MEC', 'MEC'), ('ENTC', 'ENTC'), ('AI', 'AI')], max_length=100),
        ),
        migrations.AlterField(
            model_name='facultystt',
            name='year',
            field=models.CharField(choices=[('TY', 'TY'), ('4Y', '4Y'), ('SY', 'SY'), ('FY', 'FY')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='course_name',
            field=models.CharField(choices=[('AIDS', 'AIDS'), ('CS', 'CS'), ('AIML', 'AIML'), ('IT', 'IT'), ('MEC', 'MEC'), ('ENTC', 'ENTC'), ('AI', 'AI')], default='AIML', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='year',
            field=models.CharField(choices=[('TY', 'TY'), ('4Y', '4Y'), ('SY', 'SY'), ('FY', 'FY')], default=None, max_length=2, null=True),
        ),
    ]
