# Generated by Django 5.1.7 on 2025-05-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0008_alter_facultystt_course_name_alter_facultystt_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultystt',
            name='teachersID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='facultystt',
            name='course_name',
            field=models.CharField(choices=[('AIDS', 'AIDS'), ('AI', 'AI'), ('IT', 'IT'), ('ENTC', 'ENTC'), ('MEC', 'MEC'), ('CS', 'CS'), ('AIML', 'AIML')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='course_name',
            field=models.CharField(choices=[('AIDS', 'AIDS'), ('AI', 'AI'), ('IT', 'IT'), ('ENTC', 'ENTC'), ('MEC', 'MEC'), ('CS', 'CS'), ('AIML', 'AIML')], default='AIML', max_length=100),
        ),
    ]
