# Generated by Django 5.1.7 on 2025-05-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0009_facultystt_teachersid_alter_facultystt_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultystt',
            name='course_name',
            field=models.CharField(choices=[('MEC', 'MEC'), ('AIDS', 'AIDS'), ('AI', 'AI'), ('IT', 'IT'), ('CS', 'CS'), ('ENTC', 'ENTC'), ('AIML', 'AIML')], max_length=100),
        ),
        migrations.AlterField(
            model_name='facultystt',
            name='year',
            field=models.CharField(choices=[('SY', 'SY'), ('FY', 'FY'), ('4Y', '4Y'), ('TY', 'TY')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='course_name',
            field=models.CharField(choices=[('MEC', 'MEC'), ('AIDS', 'AIDS'), ('AI', 'AI'), ('IT', 'IT'), ('CS', 'CS'), ('ENTC', 'ENTC'), ('AIML', 'AIML')], default='AIML', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='year',
            field=models.CharField(choices=[('SY', 'SY'), ('FY', 'FY'), ('4Y', '4Y'), ('TY', 'TY')], default=None, max_length=2, null=True),
        ),
    ]
