# Generated by Django 5.1.7 on 2025-05-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0011_alter_facultystt_course_name_alter_facultystt_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultystt',
            name='course_name',
            field=models.CharField(choices=[('ENTC', 'ENTC'), ('AIML', 'AIML'), ('IT', 'IT'), ('AIDS', 'AIDS'), ('CS', 'CS'), ('MEC', 'MEC'), ('AI', 'AI')], max_length=100),
        ),
        migrations.AlterField(
            model_name='facultystt',
            name='year',
            field=models.CharField(choices=[('FY', 'FY'), ('4Y', '4Y'), ('SY', 'SY'), ('TY', 'TY')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='course_name',
            field=models.CharField(choices=[('ENTC', 'ENTC'), ('AIML', 'AIML'), ('IT', 'IT'), ('AIDS', 'AIDS'), ('CS', 'CS'), ('MEC', 'MEC'), ('AI', 'AI')], default='AIML', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='year',
            field=models.CharField(choices=[('FY', 'FY'), ('4Y', '4Y'), ('SY', 'SY'), ('TY', 'TY')], default=None, max_length=2, null=True),
        ),
    ]
