# Generated by Django 5.1.7 on 2025-05-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0014_alter_facultystt_course_name_alter_facultystt_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultystt',
            name='course_name',
            field=models.CharField(choices=[('AIML', 'AIML'), ('MEC', 'MEC'), ('IT', 'IT'), ('AI', 'AI'), ('CS', 'CS'), ('ENTC', 'ENTC'), ('AIDS', 'AIDS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='facultystt',
            name='year',
            field=models.CharField(choices=[('4Y', '4Y'), ('SY', 'SY'), ('TY', 'TY'), ('FY', 'FY')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='course_name',
            field=models.CharField(choices=[('AIML', 'AIML'), ('MEC', 'MEC'), ('IT', 'IT'), ('AI', 'AI'), ('CS', 'CS'), ('ENTC', 'ENTC'), ('AIDS', 'AIDS')], default='AIML', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='year',
            field=models.CharField(choices=[('4Y', '4Y'), ('SY', 'SY'), ('TY', 'TY'), ('FY', 'FY')], default=None, max_length=2, null=True),
        ),
    ]
