# Generated by Django 5.1.7 on 2025-05-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0017_alter_facultystt_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultystt',
            name='course_name',
            field=models.CharField(choices=[('CS', 'CS'), ('MEC', 'MEC'), ('IT', 'IT'), ('AIDS', 'AIDS'), ('AIML', 'AIML'), ('AI', 'AI'), ('ENTC', 'ENTC')], max_length=100),
        ),
        migrations.AlterField(
            model_name='facultystt',
            name='year',
            field=models.CharField(choices=[('4Y', '4Y'), ('SY', 'SY'), ('FY', 'FY'), ('TY', 'TY')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='course_name',
            field=models.CharField(choices=[('CS', 'CS'), ('MEC', 'MEC'), ('IT', 'IT'), ('AIDS', 'AIDS'), ('AIML', 'AIML'), ('AI', 'AI'), ('ENTC', 'ENTC')], default='AIML', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='year',
            field=models.CharField(choices=[('4Y', '4Y'), ('SY', 'SY'), ('FY', 'FY'), ('TY', 'TY')], default=None, max_length=2, null=True),
        ),
    ]
