# Generated by Django 5.1.7 on 2025-05-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0018_alter_facultystt_course_name_alter_facultystt_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempFacultysTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('time_slot', models.CharField(choices=[('8-9 AM', '8-9 AM'), ('9-10 AM', '9-10 AM'), ('10-11 AM', '10-11 AM'), ('11-12 PM', '11-12 PM'), ('12-1 PM', '12-1 PM'), ('1-2 PM', '1-2 PM'), ('2-3 PM', '2-3 PM'), ('3-4 PM', '3-4 PM'), ('4-5 PM', '4-5 PM'), ('5-6 PM', '5-6 PM'), ('6-7 PM', '6-7 PM'), ('7-8 PM', '7-8 PM')], max_length=20)),
                ('room_no', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('class_type', models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'Lab'), ('Tutorial', 'Tutorial')], max_length=10)),
                ('course_name', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='facultystt',
            name='course_name',
            field=models.CharField(choices=[('IT', 'IT'), ('AI', 'AI'), ('ENTC', 'ENTC'), ('CS', 'CS'), ('MEC', 'MEC'), ('AIML', 'AIML'), ('AIDS', 'AIDS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='facultystt',
            name='year',
            field=models.CharField(choices=[('FY', 'FY'), ('4Y', '4Y'), ('TY', 'TY'), ('SY', 'SY')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='course_name',
            field=models.CharField(choices=[('IT', 'IT'), ('AI', 'AI'), ('ENTC', 'ENTC'), ('CS', 'CS'), ('MEC', 'MEC'), ('AIML', 'AIML'), ('AIDS', 'AIDS')], default='AIML', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='year',
            field=models.CharField(choices=[('FY', 'FY'), ('4Y', '4Y'), ('TY', 'TY'), ('SY', 'SY')], default=None, max_length=2, null=True),
        ),
    ]
