# Generated by Django 5.1.7 on 2025-05-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0020_alter_facultystt_course_name_alter_facultystt_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultystt',
            name='course_name',
            field=models.CharField(choices=[('AI', 'AI'), ('ENTC', 'ENTC'), ('IT', 'IT'), ('CS', 'CS'), ('AIDS', 'AIDS'), ('AIML', 'AIML'), ('MEC', 'MEC')], max_length=100),
        ),
        migrations.AlterField(
            model_name='facultystt',
            name='year',
            field=models.CharField(choices=[('TY', 'TY'), ('SY', 'SY'), ('4Y', '4Y'), ('FY', 'FY')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='course_name',
            field=models.CharField(choices=[('AI', 'AI'), ('ENTC', 'ENTC'), ('IT', 'IT'), ('CS', 'CS'), ('AIDS', 'AIDS'), ('AIML', 'AIML'), ('MEC', 'MEC')], default='AIML', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='year',
            field=models.CharField(choices=[('TY', 'TY'), ('SY', 'SY'), ('4Y', '4Y'), ('FY', 'FY')], default=None, max_length=2, null=True),
        ),
    ]
