# Generated by Django 5.1.7 on 2025-06-07 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0021_alter_facultystt_course_name_alter_facultystt_year_and_more'),
        ('login', '0022_alter_flogin_rank_alter_login_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultystt',
            name='course_name',
            field=models.CharField(choices=[('AIML', 'AIML'), ('ENTC', 'ENTC'), ('IT', 'IT'), ('MEC', 'MEC'), ('CS', 'CS'), ('AI', 'AI'), ('AIDS', 'AIDS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='facultystt',
            name='year',
            field=models.CharField(choices=[('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY'), ('4Y', '4Y')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='course_name',
            field=models.CharField(choices=[('AIML', 'AIML'), ('ENTC', 'ENTC'), ('IT', 'IT'), ('MEC', 'MEC'), ('CS', 'CS'), ('AI', 'AI'), ('AIDS', 'AIDS')], default='AIML', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='year',
            field=models.CharField(choices=[('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY'), ('4Y', '4Y')], default=None, max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='CanceledClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('time_slot', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.flogin')),
            ],
        ),
    ]
