# Generated by Django 5.1.7 on 2025-06-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0022_alter_facultystt_course_name_alter_facultystt_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultystt',
            name='course_name',
            field=models.CharField(choices=[('AIML', 'AIML'), ('AIDS', 'AIDS'), ('CS', 'CS'), ('AI', 'AI'), ('IT', 'IT'), ('ENTC', 'ENTC'), ('MEC', 'MEC')], max_length=100),
        ),
        migrations.AlterField(
            model_name='facultystt',
            name='year',
            field=models.CharField(choices=[('4Y', '4Y'), ('SY', 'SY'), ('FY', 'FY'), ('TY', 'TY')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='course_name',
            field=models.CharField(choices=[('AIML', 'AIML'), ('AIDS', 'AIDS'), ('CS', 'CS'), ('AI', 'AI'), ('IT', 'IT'), ('ENTC', 'ENTC'), ('MEC', 'MEC')], default='AIML', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='year',
            field=models.CharField(choices=[('4Y', '4Y'), ('SY', 'SY'), ('FY', 'FY'), ('TY', 'TY')], default=None, max_length=2, null=True),
        ),
    ]
