# Generated by Django 5.1.7 on 2025-06-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0023_alter_facultystt_course_name_alter_facultystt_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultystt',
            name='course_name',
            field=models.CharField(choices=[('CS', 'CS'), ('CSAIML', 'CSAIML'), ('CSAI', 'CSAI'), ('IT', 'IT'), ('AIDS', 'AIDS'), ('MEC', 'MEC'), ('ENTC', 'ENTC')], max_length=100),
        ),
        migrations.AlterField(
            model_name='facultystt',
            name='year',
            field=models.CharField(choices=[('FY', 'FY'), ('TY', 'TY'), ('4Y', '4Y'), ('SY', 'SY')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='course_name',
            field=models.CharField(choices=[('CS', 'CS'), ('CSAIML', 'CSAIML'), ('CSAI', 'CSAI'), ('IT', 'IT'), ('AIDS', 'AIDS'), ('MEC', 'MEC'), ('ENTC', 'ENTC')], default='AIML', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='year',
            field=models.CharField(choices=[('FY', 'FY'), ('TY', 'TY'), ('4Y', '4Y'), ('SY', 'SY')], default=None, max_length=2, null=True),
        ),
    ]
