# Generated by Django 5.1.7 on 2025-06-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0024_alter_facultystt_course_name_alter_facultystt_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempfacultystt',
            name='batch',
            field=models.CharField(default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='tempfacultystt',
            name='teachersID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tempfacultystt',
            name='year',
            field=models.CharField(default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='facultystt',
            name='year',
            field=models.CharField(choices=[('SY', 'SY'), ('4Y', '4Y'), ('TY', 'TY'), ('FY', 'FY')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='year',
            field=models.CharField(choices=[('SY', 'SY'), ('4Y', '4Y'), ('TY', 'TY'), ('FY', 'FY')], default=None, max_length=2, null=True),
        ),
    ]
