# Generated by Django 5.1.7 on 2025-06-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0025_tempfacultystt_batch_tempfacultystt_teachersid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canceledclass',
            name='batch',
            field=models.CharField(default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='canceledclass',
            name='class_type',
            field=models.CharField(default='Theory', max_length=10),
        ),
        migrations.AddField(
            model_name='canceledclass',
            name='course_name',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='canceledclass',
            name='division',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='canceledclass',
            name='subject_name',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='facultystt',
            name='year',
            field=models.CharField(choices=[('4Y', '4Y'), ('TY', 'TY'), ('SY', 'SY'), ('FY', 'FY')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='year',
            field=models.CharField(choices=[('4Y', '4Y'), ('TY', 'TY'), ('SY', 'SY'), ('FY', 'FY')], default=None, max_length=2, null=True),
        ),
    ]
