# Generated by Django 5.1.7 on 2025-06-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0026_canceledclass_batch_canceledclass_class_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canceledclass',
            name='teacher_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facultystt',
            name='year',
            field=models.CharField(choices=[('SY', 'SY'), ('FY', 'FY'), ('TY', 'TY'), ('4Y', '4Y')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='year',
            field=models.CharField(choices=[('SY', 'SY'), ('FY', 'FY'), ('TY', 'TY'), ('4Y', '4Y')], default=None, max_length=2, null=True),
        ),
    ]
