# Generated by Django 5.1.7 on 2025-06-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0027_alter_canceledclass_teacher_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canceledclass',
            name='room_no',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='facultystt',
            name='year',
            field=models.CharField(choices=[('SY', 'SY'), ('4Y', '4Y'), ('FY', 'FY'), ('TY', 'TY')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='year',
            field=models.CharField(choices=[('SY', 'SY'), ('4Y', '4Y'), ('FY', 'FY'), ('TY', 'TY')], default=None, max_length=2, null=True),
        ),
    ]
