# Generated by Django 5.1.7 on 2025-06-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0028_canceledclass_room_no_alter_facultystt_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultystt',
            name='year',
            field=models.CharField(choices=[('4Y', '4Y'), ('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentstt',
            name='year',
            field=models.CharField(choices=[('4Y', '4Y'), ('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY')], default=None, max_length=2, null=True),
        ),
    ]
