# Generated by Django 5.1.4 on 2025-04-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='branch',
            field=models.CharField(blank=True, choices=[('AIML', 'Artificial Intelligence and Machine Learning'), ('CS', 'Computer Science'), ('AIDS', 'Artificial Intelligence and Data Science')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='div',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
    ]
