# Generated by Django 5.1.4 on 2025-04-12 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_flogin_login_branch_login_div'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='role',
        ),
    ]
