# Generated by Django 5.1.4 on 2025-04-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_login_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='Name',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='batch',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='branch',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
