# Generated by Django 5.1.4 on 2025-04-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_login_name_login_batch_login_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flogin',
            name='Name',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
