# Generated by Django 5.1.7 on 2025-05-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_flogin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flogin',
            name='fNo',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='year',
            field=models.CharField(choices=[('TY', 'TY'), ('SY', 'SY'), ('4Y', '4Y'), ('FY', 'FY')], default=None, max_length=2, null=True),
        ),
    ]
