# Generated by Django 5.1.7 on 2025-05-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_login_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flogin',
            name='fNo',
        ),
        migrations.AddField(
            model_name='flogin',
            name='teachersID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='login',
            name='year',
            field=models.CharField(choices=[('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY'), ('4Y', '4Y')], default=None, max_length=2, null=True),
        ),
    ]
