# Generated by Django 5.1.7 on 2025-05-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_remove_flogin_fno_flogin_teachersid_alter_login_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='branch',
            new_name='course_name',
        ),
        migrations.AlterField(
            model_name='login',
            name='year',
            field=models.CharField(choices=[('FY', 'FY'), ('4Y', '4Y'), ('TY', 'TY'), ('SY', 'SY')], default=None, max_length=2, null=True),
        ),
    ]
