# Generated by Django 5.1.7 on 2025-05-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_alter_login_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='flogin',
            name='dept',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flogin',
            name='rank',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Assistant Professor', 'Assistant Professor')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flogin',
            name='Name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flogin',
            name='Password',
            field=models.CharField(default='vitpune', max_length=10),
        ),
        migrations.AlterField(
            model_name='flogin',
            name='userName',
            field=models.EmailField(default='xyz@vit.edu', max_length=254),
        ),
        migrations.AlterField(
            model_name='login',
            name='year',
            field=models.CharField(choices=[('FY', 'FY'), ('TY', 'TY'), ('SY', 'SY'), ('4Y', '4Y')], default=None, max_length=2, null=True),
        ),
    ]
