# Generated by Django 5.1.7 on 2025-05-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_flogin_dept_flogin_rank_alter_flogin_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='year',
            field=models.CharField(choices=[('TY', 'TY'), ('4Y', '4Y'), ('FY', 'FY'), ('SY', 'SY')], default=None, max_length=2, null=True),
        ),
    ]
