# Generated by Django 5.1.7 on 2025-05-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_alter_flogin_rank_alter_login_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flogin',
            name='rank',
            field=models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Professor', 'Professor')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='year',
            field=models.CharField(choices=[('TY', 'TY'), ('SY', 'SY'), ('4Y', '4Y'), ('FY', 'FY')], default=None, max_length=2, null=True),
        ),
    ]
