# Generated by Django 5.1.7 on 2025-06-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_alter_flogin_rank_alter_login_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='year',
            field=models.CharField(choices=[('FY', 'FY'), ('TY', 'TY'), ('4Y', '4Y'), ('SY', 'SY')], default=None, max_length=2, null=True),
        ),
    ]
