# Generated by Django 5.1.7 on 2025-06-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_alter_flogin_rank_alter_login_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='year',
            field=models.CharField(choices=[('4Y', '4Y'), ('TY', 'TY'), ('SY', 'SY'), ('FY', 'FY')], default=None, max_length=2, null=True),
        ),
    ]
