# Generated by Django 5.1.7 on 2025-06-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_alter_login_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flogin',
            name='rank',
            field=models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Professor', 'Professor')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='year',
            field=models.CharField(choices=[('SY', 'SY'), ('FY', 'FY'), ('TY', 'TY'), ('4Y', '4Y')], default=None, max_length=2, null=True),
        ),
    ]
