# Generated by Django 5.1.7 on 2025-06-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_alter_flogin_rank_alter_login_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='year',
            field=models.CharField(choices=[('SY', 'SY'), ('4Y', '4Y'), ('FY', 'FY'), ('TY', 'TY')], default=None, max_length=2, null=True),
        ),
    ]
