# Generated by Django 5.1.7 on 2025-06-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_alter_login_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flogin',
            name='rank',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Assistant Professor', 'Assistant Professor')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='year',
            field=models.CharField(choices=[('4Y', '4Y'), ('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY')], default=None, max_length=2, null=True),
        ),
    ]
