# Generated by Django 5.1.7 on 2025-06-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('years', models.JSONField(default=list)),
                ('branches', models.JSONField(default=list)),
                ('sections', models.JSONField(default=list)),
                ('batches', models.JSONField(default=list)),
                ('teacher_id', models.CharField(max_length=20)),
                ('teacher_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
